THIS ISN'T WORKING.
so it works for a bit on the compression, BUT... eventually i invariably get a:

Traceback (most recent call last):
  File "/tmp/sksdump.py", line 163, in <module>
    main()
  File "/tmp/sksdump.py", line 159, in main
    compressDB()
  File "/tmp/sksdump.py", line 135, in compressDB
    fh_out.write(lrzip.compress(fh_in.read()))
OSError: [Errno 9] Bad file descriptor

So. I'm gonna try it outside of a with.